name: Git Bisect Automation
on: [push]

jobs:
  bisect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install packages
        run: pip install -r requirements.txt

      - name: Run Git Bisect
        run: |
          # Initialisation du bisect
          git bisect start
          git bisect bad HEAD
          git bisect good e4cfc6f77ebbe2e23550ddab682316ab4ce1c03c

          # Script automatique de test pour bisect
          git bisect run bash -c "python manage.py test > result.log 2>&1 || exit 1"

          # Fin du bisect
          git bisect reset
